version: '3.7'

services:
  backend:
    build: 
      context: ./backend
    hostname: backend
    ports:
      - "8000:8000"

  frontend:
    build: ./ui
    hostname: frontend
    environment:
      REACT_APP_API_URL: 'http://157.230.125.5:8000,'
    ports:
      - "3000:3000"
    depends_on:
      - backend
  db:
    image: postgres:15.3-alpine
    hostname: db
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 5432:5432
